# 以下は本番環境ではPostgreSQLを使用するため、以下のようにdatabase.ymlの設定を変更内容

default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: all_procedure_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: all_procedure_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>